version: '2'
volumes:
  dbdata:
services:
  wp_documentor_db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wp_documentor_db
  wp_documentor_wp:
    depends_on:
      - wp_documentor_db
    image: wordpress:php7.4-apache
    ports:
      - "5000:80"
    restart: always
    environment:
      WORDPRESS_ENVIRONMENT: development
      WORDPRESS_DB_HOST: wp_documentor_db:3306
      WORDPRESS_DB_NAME: wp_documentor_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/wp-content/themes/wp-documentor